on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy API doc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: bump-sh/github-action@0.1
        with:
          id: ${{ secrets.DOC_ID }}
          token: ${{ secrets.DOC_TOKEN }}
          file: openapi.yaml