on:
  push:
    branches-ignore:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Validate API doc
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Validate
        uses: bump-sh/github-action@0.1
        with:
          id: ${{ secrets.DOC_ID }}
          token: ${{ secrets.DOC_TOKEN }}
          file: docs/openapi.yaml
          command: validate